[package]
name = "btdu-rs"
version = "0.1.0"
edition = "2021"

[profile.reldebug]
inherits = "release"
debug = true

[dependencies]
nix = "0.23.0"
anyhow = "1.0.47"
bytesize = "1.1.0"
rand = "0.8.4"
# sequence_trie = "0.3.6"
pretty-hex = "0.2.1"
